import type { Tool } from './types'

// Hardcoded tool data — werkt zonder database
// Later te vervangen door Supabase queries

export const TOOLS: Tool[] = [
  {
    id: '1',
    slug: 'chatgpt',
    naam: 'ChatGPT',
    tagline: 'De bekendste AI-chatbot ter wereld',
    beschrijving: 'ChatGPT van OpenAI is de meest gebruikte AI-assistent. Je kunt er mee chatten, teksten schrijven, code debuggen, vragen beantwoorden en veel meer. De gratis versie biedt toegang tot GPT-4o mini, de Plus-versie geeft onbeperkte toegang tot GPT-4o inclusief DALL-E 3 beeldgeneratie.',
    logo_url: null,
    website_url: 'https://chatgpt.com',
    affiliate_url: null,
    categorie: 'chatbot',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['GPT-4o mini', '40 berichten per dag', 'Basis beeldgeneratie'], aanbevolen: false },
      { naam: 'Plus', prijs_mnd: 22, prijs_jaar: 220, functies: ['GPT-4o onbeperkt', 'DALL-E 3', 'Geavanceerde analyse', 'Plugins'], aanbevolen: true },
      { naam: 'Team', prijs_mnd: 30, prijs_jaar: 300, functies: ['Alles van Plus', 'Workspace beheer', 'Geen trainingsdata'], aanbevolen: false },
    ],
    beoordeling: 4.7,
    uitgelicht: true,
    badge: 'Populair',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '2',
    slug: 'claude',
    naam: 'Claude',
    tagline: 'De slimste AI-assistent van Anthropic',
    beschrijving: 'Claude van Anthropic staat bekend om zijn lange contextvenster, nuance en veiligheid. Uitstekend voor het analyseren van lange documenten, schrijven van kwalitatieve teksten en complexe redenering. De gratis versie is al indrukwekkend.',
    logo_url: null,
    website_url: 'https://claude.ai',
    affiliate_url: null,
    categorie: 'chatbot',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['Claude Sonnet', 'Beperkte berichten per dag', '200K token context'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 22, prijs_jaar: 220, functies: ['Claude Opus 4', '5x meer gebruik', 'Projecten', 'Prioriteit toegang'], aanbevolen: true },
    ],
    beoordeling: 4.6,
    uitgelicht: true,
    badge: 'Aanbevolen',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '3',
    slug: 'gemini',
    naam: 'Gemini',
    tagline: "Google's krachtige multimodale AI",
    beschrijving: 'Gemini van Google combineert tekst, beeld en code in één model. Diep geïntegreerd met Google Workspace (Docs, Gmail, Drive). Ideaal als je al in het Google-ecosysteem werkt.',
    logo_url: null,
    website_url: 'https://gemini.google.com',
    affiliate_url: null,
    categorie: 'chatbot',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['Gemini 1.5 Flash', 'Google integraties', 'Beeldanalyse'], aanbevolen: false },
      { naam: 'Advanced', prijs_mnd: 22, prijs_jaar: 219, functies: ['Gemini 1.5 Ultra', 'Google One 2TB', 'Workspace AI'], aanbevolen: true },
    ],
    beoordeling: 4.3,
    uitgelicht: true,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '4',
    slug: 'grok',
    naam: 'Grok',
    tagline: "xAI's ongefiltreerde AI-chatbot",
    beschrijving: "Grok van Elon Musk's xAI is een AI-chatbot met realtime toegang tot X (Twitter). Staat bekend om directe, ongefiltreerde antwoorden en humoristische stijl. Beschikbaar voor X Premium+ abonnees en via de Grok-app.",
    logo_url: null,
    website_url: 'https://grok.x.ai',
    affiliate_url: null,
    categorie: 'chatbot',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['Grok-2 basis', '10 berichten per uur', 'Beeldgeneratie'], aanbevolen: false },
      { naam: 'Premium+', prijs_mnd: 16, prijs_jaar: 168, functies: ['Grok-2 onbeperkt', 'Realtime X data', 'Geen wachtrij'], aanbevolen: true },
      { naam: 'SuperGrok', prijs_mnd: 30, prijs_jaar: 300, functies: ['Grok-3 toegang', 'Maximaal gebruik', 'Geavanceerde analyse'], aanbevolen: false },
    ],
    beoordeling: 4.1,
    uitgelicht: true,
    badge: 'Nieuw',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '5',
    slug: 'perplexity',
    naam: 'Perplexity',
    tagline: 'AI-zoekmachine met live bronnen',
    beschrijving: 'Perplexity is een AI-zoekmachine die antwoorden geeft met directe bronvermeldingen. Perfect voor research en up-to-date informatie. Anders dan ChatGPT heeft het altijd toegang tot internet.',
    logo_url: null,
    website_url: 'https://perplexity.ai',
    affiliate_url: null,
    categorie: 'chatbot',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['Onbeperkt zoeken', 'Basis AI-modellen', 'Bronnenvermeldingen'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 22, prijs_jaar: 200, functies: ['GPT-4o & Claude', 'Onbeperkte uploads', 'Geavanceerde analyse'], aanbevolen: true },
    ],
    beoordeling: 4.4,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '6',
    slug: 'copilot',
    naam: 'Microsoft Copilot',
    tagline: 'AI van Microsoft gratis in Windows',
    beschrijving: 'Microsoft Copilot is gratis beschikbaar en gebouwd op GPT-4. Diep geïntegreerd in Windows 11, Edge en Microsoft 365. Ideaal voor gebruikers die al met Microsoft-producten werken.',
    logo_url: null,
    website_url: 'https://copilot.microsoft.com',
    affiliate_url: null,
    categorie: 'chatbot',
    prijsmodel: 'gratis',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['GPT-4', 'Onbeperkt gebruik', 'Windows integratie', 'DALL-E beelden'], aanbevolen: true },
    ],
    beoordeling: 4.0,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '7',
    slug: 'poe',
    naam: 'Poe',
    tagline: 'Toegang tot alle AI-modellen in één app',
    beschrijving: 'Poe van Quora biedt toegang tot ChatGPT, Claude, Gemini, Llama en meer in één interface. Je kunt eigen bots maken en delen. Ideaal als je meerdere AI-modellen wilt vergelijken.',
    logo_url: null,
    website_url: 'https://poe.com',
    affiliate_url: null,
    categorie: 'chatbot',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['Dagelijkse credits', 'Meerdere modellen', 'Community bots'], aanbevolen: false },
      { naam: 'Subscriber', prijs_mnd: 20, prijs_jaar: 200, functies: ['Onbeperkt GPT-4o', 'Onbeperkt Claude', 'Eigen bots'], aanbevolen: true },
    ],
    beoordeling: 4.2,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '8',
    slug: 'midjourney',
    naam: 'Midjourney',
    tagline: 'De gouden standaard voor AI-kunst',
    beschrijving: 'Midjourney produceert de mooiste en meest artistieke AI-afbeeldingen. Geen gratis tier, maar de kwaliteit rechtvaardigt de prijs. Populair bij designers, marketeers en creatieven.',
    logo_url: null,
    website_url: 'https://midjourney.com',
    affiliate_url: null,
    categorie: 'afbeelding',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Basic', prijs_mnd: 12, prijs_jaar: 96, functies: ['200 afbeeldingen/mnd', 'Persoonlijk gebruik'], aanbevolen: false },
      { naam: 'Standard', prijs_mnd: 30, prijs_jaar: 288, functies: ['Onbeperkt relaxed', '15u fast GPU', 'Commercieel'], aanbevolen: true },
      { naam: 'Pro', prijs_mnd: 60, prijs_jaar: 576, functies: ['Alles van Standard', '30u fast GPU', 'Stealth modus'], aanbevolen: false },
    ],
    beoordeling: 4.8,
    uitgelicht: true,
    badge: 'Populair',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '9',
    slug: 'dall-e',
    naam: 'DALL-E 3',
    tagline: "OpenAI's afbeeldingsgenerator",
    beschrijving: 'DALL-E 3 is beschikbaar via ChatGPT en de OpenAI API. Uitstekend in het begrijpen van gedetailleerde omschrijvingen en het genereren van fotorealistische beelden.',
    logo_url: null,
    website_url: 'https://openai.com/dall-e-3',
    affiliate_url: null,
    categorie: 'afbeelding',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Via ChatGPT Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['Beperkte generaties', 'Lagere kwaliteit'], aanbevolen: false },
      { naam: 'Via ChatGPT Plus', prijs_mnd: 22, prijs_jaar: 220, functies: ['Hogere kwaliteit', 'Meer generaties', 'HD modus'], aanbevolen: true },
    ],
    beoordeling: 4.2,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '10',
    slug: 'adobe-firefly',
    naam: 'Adobe Firefly',
    tagline: 'AI-beelden veilig voor commercieel gebruik',
    beschrijving: 'Adobe Firefly is getraind op gelicenseerde content, waardoor alle gegenereerde beelden veilig zijn voor commercieel gebruik. Ingebouwd in Photoshop en Illustrator.',
    logo_url: null,
    website_url: 'https://firefly.adobe.com',
    affiliate_url: null,
    categorie: 'afbeelding',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['25 generaties/mnd', 'Watermark'], aanbevolen: false },
      { naam: 'Premium', prijs_mnd: 5, prijs_jaar: 50, functies: ['100 generaties', 'Geen watermark', 'Alle functies'], aanbevolen: true },
    ],
    beoordeling: 4.1,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '11',
    slug: 'ideogram',
    naam: 'Ideogram',
    tagline: 'AI-afbeeldingen met perfecte tekst',
    beschrijving: 'Ideogram is de beste AI-tool voor afbeeldingen met leesbare tekst erin. Populair voor posters, social media en marketing.',
    logo_url: null,
    website_url: 'https://ideogram.ai',
    affiliate_url: null,
    categorie: 'afbeelding',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['10 generaties/dag', 'Publiek'], aanbevolen: false },
      { naam: 'Basic', prijs_mnd: 8, prijs_jaar: 80, functies: ['400 generaties/mnd', 'Privé', 'Prioriteit'], aanbevolen: true },
    ],
    beoordeling: 4.3,
    uitgelicht: false,
    badge: 'Nieuw',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '12',
    slug: 'stable-diffusion',
    naam: 'Stable Diffusion',
    tagline: 'Open-source AI-beeldgenerator',
    beschrijving: 'Stable Diffusion is volledig gratis en open-source. Je kunt het lokaal draaien of via platforms als Automatic1111. Maximale controle, maar vereist technische kennis.',
    logo_url: null,
    website_url: 'https://stability.ai',
    affiliate_url: null,
    categorie: 'afbeelding',
    prijsmodel: 'gratis',
    plannen: [
      { naam: 'Open-source', prijs_mnd: 0, prijs_jaar: 0, functies: ['Volledig gratis', 'Lokaal draaien', 'Onbeperkt', 'Community modellen'], aanbevolen: true },
    ],
    beoordeling: 4.0,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '13',
    slug: 'runway',
    naam: 'Runway Gen-3',
    tagline: 'Professionele AI-videobewerking',
    beschrijving: 'Runway is de favoriete AI-videotool van professionals. Gen-3 Alpha genereert indrukwekkende video\'s van tekst of afbeeldingen. Breed gebruikt in de filmindustrie.',
    logo_url: null,
    website_url: 'https://runwayml.com',
    affiliate_url: null,
    categorie: 'video',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['125 credits', '720p export', 'Watermark'], aanbevolen: false },
      { naam: 'Standard', prijs_mnd: 15, prijs_jaar: 144, functies: ['625 credits/mnd', '1080p', 'Geen watermark'], aanbevolen: true },
      { naam: 'Pro', prijs_mnd: 35, prijs_jaar: 336, functies: ['2250 credits', '4K', 'Commercieel'], aanbevolen: false },
    ],
    beoordeling: 4.5,
    uitgelicht: true,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '14',
    slug: 'sora',
    naam: 'Sora',
    tagline: "OpenAI's hyperrealistische videogenerator",
    beschrijving: 'Sora van OpenAI genereert tot 20 seconden hyperrealistische video van een tekstbeschrijving. Beschikbaar voor ChatGPT Plus en Pro abonnees. Baanbrekend in kwaliteit.',
    logo_url: null,
    website_url: 'https://sora.com',
    affiliate_url: null,
    categorie: 'video',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Via ChatGPT Plus', prijs_mnd: 22, prijs_jaar: 220, functies: ["50 video's/mnd", '480p', '5 sec max'], aanbevolen: false },
      { naam: 'Via ChatGPT Pro', prijs_mnd: 220, prijs_jaar: 2200, functies: ["500 video's/mnd", '1080p', '20 sec max'], aanbevolen: true },
    ],
    beoordeling: 4.4,
    uitgelicht: false,
    badge: 'Nieuw',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '15',
    slug: 'kling',
    naam: 'Kling AI',
    tagline: 'Krachtige Chinese AI-videogenerator',
    beschrijving: 'Kling van Kuaishou is een snel opkomende concurrent van Sora en Runway. Genereert indrukwekkende video\'s met een royaal gratis tier.',
    logo_url: null,
    website_url: 'https://klingai.com',
    affiliate_url: null,
    categorie: 'video',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['166 credits/mnd', '720p', '5 seconden'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 35, prijs_jaar: 299, functies: ['3000 credits', '1080p', '2 min video'], aanbevolen: true },
    ],
    beoordeling: 4.2,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '16',
    slug: 'cursor',
    naam: 'Cursor',
    tagline: 'De AI-code-editor voor developers',
    beschrijving: 'Cursor is een fork van VS Code met diepgaande AI-integratie. Je kunt code genereren, debuggen en refactoren met natuurlijke taal. Begrijpt je hele codebase. De favoriet van veel professionele developers.',
    logo_url: null,
    website_url: 'https://cursor.com',
    affiliate_url: null,
    categorie: 'coding',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Hobby', prijs_mnd: 0, prijs_jaar: 0, functies: ['2000 completions', '50 slow premium requests', 'VS Code fork'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 20, prijs_jaar: 192, functies: ['Onbeperkte completions', '500 premium requests', 'Snellere modellen'], aanbevolen: true },
    ],
    beoordeling: 4.7,
    uitgelicht: true,
    badge: 'Aanbevolen',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '17',
    slug: 'github-copilot',
    naam: 'GitHub Copilot',
    tagline: 'AI-assistent ingebouwd in je IDE',
    beschrijving: 'GitHub Copilot integreert in VS Code, JetBrains en meer. Genereert code suggesties terwijl je typt en beantwoordt vragen over je code.',
    logo_url: null,
    website_url: 'https://github.com/features/copilot',
    affiliate_url: null,
    categorie: 'coding',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Individual', prijs_mnd: 10, prijs_jaar: 100, functies: ['Onbeperkte suggesties', 'Chat', 'CLI integratie'], aanbevolen: true },
      { naam: 'Business', prijs_mnd: 19, prijs_jaar: 228, functies: ['Alles van Individual', 'Teambeleid', 'Audit logs'], aanbevolen: false },
    ],
    beoordeling: 4.3,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '18',
    slug: 'claude-code',
    naam: 'Claude Code',
    tagline: "Anthropic's AI coding agent in je terminal",
    beschrijving: 'Claude Code is een CLI-tool van Anthropic waarmee je hele projecten kunt bouwen, debuggen en refactoren via natuurlijke taal. Begrijpt je volledige codebase en kan zelfstandig bestanden aanmaken en bewerken.',
    logo_url: null,
    website_url: 'https://claude.ai/code',
    affiliate_url: null,
    categorie: 'coding',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Via Claude Pro', prijs_mnd: 22, prijs_jaar: 220, functies: ['Sonnet-toegang', 'Basis usage', 'IDE integraties'], aanbevolen: false },
      { naam: 'Via Claude Max', prijs_mnd: 100, prijs_jaar: 1000, functies: ['Opus-toegang', '5x meer gebruik', 'Onbeperkt code'], aanbevolen: true },
    ],
    beoordeling: 4.8,
    uitgelicht: true,
    badge: 'Aanbevolen',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '19',
    slug: 'windsurf',
    naam: 'Windsurf',
    tagline: 'AI-code-editor met diep contextbegrip',
    beschrijving: 'Windsurf (voorheen Codeium) is een krachtig alternatief voor Cursor met een eigen AI-engine genaamd Cascade. Begrijpt je gehele codebase en kan meerdere bestanden tegelijk aanpassen.',
    logo_url: null,
    website_url: 'https://windsurf.com',
    affiliate_url: null,
    categorie: 'coding',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['Onbeperkte completions', '25 Flow credits', 'Cascade toegang'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 15, prijs_jaar: 144, functies: ['Onbeperkte completions', '500 Flow credits', 'Geavanceerde modellen'], aanbevolen: true },
    ],
    beoordeling: 4.5,
    uitgelicht: false,
    badge: 'Nieuw',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '20',
    slug: 'v0',
    naam: 'v0',
    tagline: 'AI UI-builder van Vercel',
    beschrijving: 'v0 van Vercel genereert complete React-componenten en webpagina\'s van een tekstomschrijving of screenshot. Produceert productie-klare code met Tailwind CSS.',
    logo_url: null,
    website_url: 'https://v0.dev',
    affiliate_url: null,
    categorie: 'coding',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['200 berichten/mnd', 'Basis generaties', 'Code export'], aanbevolen: false },
      { naam: 'Premium', prijs_mnd: 20, prijs_jaar: 200, functies: ['Onbeperkte berichten', 'Prioriteit', 'Geavanceerde modellen'], aanbevolen: true },
    ],
    beoordeling: 4.4,
    uitgelicht: false,
    badge: 'Nieuw',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '21',
    slug: 'elevenlabs',
    naam: 'ElevenLabs',
    tagline: 'Meest realistische AI-stemmen',
    beschrijving: 'ElevenLabs maakt de meest overtuigende AI-stemmen beschikbaar. Je kunt elke tekst omzetten naar spraak, bestaande stemmen klonen of je eigen stem aanmaken.',
    logo_url: null,
    website_url: 'https://elevenlabs.io',
    affiliate_url: null,
    categorie: 'audio',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['10.000 tekens/mnd', '3 aangepaste stemmen'], aanbevolen: false },
      { naam: 'Starter', prijs_mnd: 5, prijs_jaar: 50, functies: ['30.000 tekens', '10 stemmen', 'Commercieel'], aanbevolen: true },
      { naam: 'Creator', prijs_mnd: 22, prijs_jaar: 220, functies: ['100.000 tekens', 'Professionele kloning'], aanbevolen: false },
    ],
    beoordeling: 4.6,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '22',
    slug: 'suno',
    naam: 'Suno',
    tagline: 'Volledige nummers genereren met AI',
    beschrijving: 'Suno genereert complete liedjes — inclusief zang, instrumenten en productie — van een simpele tekstomschrijving. Baanbrekend voor iedereen die muziek wil maken.',
    logo_url: null,
    website_url: 'https://suno.com',
    affiliate_url: null,
    categorie: 'audio',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['50 credits/dag', 'Niet-commercieel', '2 nummers tegelijk'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 10, prijs_jaar: 96, functies: ['2500 credits/mnd', 'Commercieel', 'Geen wachtrij'], aanbevolen: true },
    ],
    beoordeling: 4.4,
    uitgelicht: false,
    badge: 'Populair',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '23',
    slug: 'notion-ai',
    naam: 'Notion AI',
    tagline: 'AI ingebouwd in je werkruimte',
    beschrijving: 'Notion AI voegt AI-functies toe aan Notion: tekst schrijven, samenvatten, vertalen, actiepunten extraheren en meer. Ideaal als je Notion al gebruikt.',
    logo_url: null,
    website_url: 'https://notion.so/product/ai',
    affiliate_url: null,
    categorie: 'productiviteit',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Notion AI add-on', prijs_mnd: 10, prijs_jaar: 96, functies: ['Onbeperkt AI-gebruik', 'Alle Notion functies', 'Team samenwerking'], aanbevolen: true },
    ],
    beoordeling: 4.2,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '24',
    slug: 'gamma',
    naam: 'Gamma',
    tagline: 'Presentaties maken met AI',
    beschrijving: 'Gamma maakt in seconden professionele presentaties, documenten en websites van een prompt. Geen PowerPoint kennis nodig. Populair bij studenten en ondernemers.',
    logo_url: null,
    website_url: 'https://gamma.app',
    affiliate_url: null,
    categorie: 'productiviteit',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['400 AI-credits', 'Onbeperkte weergaven', 'Gamma-branding'], aanbevolen: false },
      { naam: 'Plus', prijs_mnd: 10, prijs_jaar: 96, functies: ['Onbeperkt AI', 'Geen branding', 'Aangepaste domeinen'], aanbevolen: true },
    ],
    beoordeling: 4.3,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '25',
    slug: 'jasper',
    naam: 'Jasper',
    tagline: 'AI-platform voor marketing content',
    beschrijving: 'Jasper is het toonaangevende AI-platform voor marketingteams. Schrijf blogposts, social media content, advertentieteksten en meer in je eigen brand voice.',
    logo_url: null,
    website_url: 'https://jasper.ai',
    affiliate_url: null,
    categorie: 'productiviteit',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Creator', prijs_mnd: 49, prijs_jaar: 468, functies: ['1 brand voice', 'SEO modus', 'Afbeeldingsgeneratie'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 69, prijs_jaar: 660, functies: ['3 brand voices', 'Kennis assets', 'Campagne toolkit'], aanbevolen: true },
    ],
    beoordeling: 4.0,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  // --- Hidden gems: lucratieve affiliate tools ---
  {
    id: '26',
    slug: 'synthesia',
    naam: 'Synthesia',
    tagline: 'Maak professionele video\'s met AI-avatars',
    beschrijving: 'Synthesia maakt het mogelijk om professionele video\'s te maken met levensechte AI-avatars, zonder camera of studio. Kies uit 150+ avatars in 120+ talen. Populair bij bedrijven voor trainingen, marketing en interne communicatie.',
    logo_url: null,
    website_url: 'https://www.synthesia.io',
    affiliate_url: null,
    categorie: 'video',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Starter', prijs_mnd: 22, prijs_jaar: 216, functies: ['120 minuten video/jaar', '90+ AI-avatars', '120+ talen'], aanbevolen: false },
      { naam: 'Creator', prijs_mnd: 67, prijs_jaar: 648, functies: ['360 minuten video/jaar', 'Eigen avatar', 'Merkkleuren'], aanbevolen: true },
    ],
    beoordeling: 4.5,
    uitgelicht: false,
    badge: 'Tip',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '27',
    slug: 'descript',
    naam: 'Descript',
    tagline: 'Bewerk video en audio als een document',
    beschrijving: 'Descript is een revolutionaire video- en audio-editor. Bewerk video door tekst te bewerken — verwijder woorden uit het transcript en ze verdwijnen uit de video. Inclusief AI-schermopname, ondertiteling en filler word verwijdering.',
    logo_url: null,
    website_url: 'https://www.descript.com',
    affiliate_url: null,
    categorie: 'video',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['1 uur transcriptie/mnd', 'Watermark', 'Basis export'], aanbevolen: false },
      { naam: 'Hobbyist', prijs_mnd: 24, prijs_jaar: 192, functies: ['10 uur transcriptie', 'Geen watermark', 'AI-functies'], aanbevolen: false },
      { naam: 'Business', prijs_mnd: 33, prijs_jaar: 288, functies: ['30 uur transcriptie', 'AI-stemkloon', 'Teamfuncties'], aanbevolen: true },
    ],
    beoordeling: 4.4,
    uitgelicht: false,
    badge: 'Tip',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '28',
    slug: 'pictory',
    naam: 'Pictory',
    tagline: 'Maak video\'s van artikelen en scripts',
    beschrijving: 'Pictory transformeert blogposts, artikelen en scripts automatisch in professionele korte video\'s. Ideaal voor content creators die hun bereik willen vergroten met video zonder expertise.',
    logo_url: null,
    website_url: 'https://pictory.ai',
    affiliate_url: null,
    categorie: 'video',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Starter', prijs_mnd: 19, prijs_jaar: 190, functies: ['30 video\'s/mnd', '10 min per video', 'AI-voice-over'], aanbevolen: false },
      { naam: 'Professional', prijs_mnd: 39, prijs_jaar: 390, functies: ['60 video\'s/mnd', '20 min per video', 'Merkkleuren'], aanbevolen: true },
    ],
    beoordeling: 4.1,
    uitgelicht: false,
    badge: 'Tip',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '29',
    slug: 'murf-ai',
    naam: 'Murf AI',
    tagline: 'Professionele AI-voice-overs in minuten',
    beschrijving: 'Murf AI biedt 120+ hyperrealistische AI-stemmen in 20+ talen. Maak voice-overs voor video\'s, presentaties, podcasts en e-learning zonder voice-over artiest.',
    logo_url: null,
    website_url: 'https://murf.ai',
    affiliate_url: null,
    categorie: 'audio',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['10 min generatie', 'Beperkte stemmen', 'Watermark'], aanbevolen: false },
      { naam: 'Creator', prijs_mnd: 26, prijs_jaar: 234, functies: ['48 uur/jaar', '120+ stemmen', 'Commercieel'], aanbevolen: true },
    ],
    beoordeling: 4.3,
    uitgelicht: false,
    badge: 'Tip',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '30',
    slug: 'copy-ai',
    naam: 'Copy.ai',
    tagline: 'AI-copywriting voor marketing teams',
    beschrijving: 'Copy.ai is gespecialiseerd in marketing content: advertentieteksten, productbeschrijvingen, e-mails, social media posts en meer. Met workflows kun je repetitieve content-taken automatiseren.',
    logo_url: null,
    website_url: 'https://www.copy.ai',
    affiliate_url: null,
    categorie: 'productiviteit',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['2.000 woorden/mnd', '1 gebruiker', '90+ templates'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 36, prijs_jaar: 324, functies: ['Onbeperkte woorden', '5 gebruikers', 'Workflows', 'Brand voices'], aanbevolen: true },
    ],
    beoordeling: 4.2,
    uitgelicht: false,
    badge: 'Tip',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '31',
    slug: 'writesonic',
    naam: 'Writesonic',
    tagline: 'AI-schrijfassistent met SEO-focus',
    beschrijving: 'Writesonic combineert AI-writing met SEO-tools. Genereer SEO-geoptimaliseerde blogs, landingspagina\'s en advertenties. Inclusief Chatsonic — een ChatGPT-alternatief met real-time informatie.',
    logo_url: null,
    website_url: 'https://writesonic.com',
    affiliate_url: null,
    categorie: 'productiviteit',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['10.000 woorden/mnd', 'Chatsonic', 'Basis functies'], aanbevolen: false },
      { naam: 'Individual', prijs_mnd: 16, prijs_jaar: 156, functies: ['Onbeperkt woorden', 'SEO Checker', 'Brand voice'], aanbevolen: true },
    ],
    beoordeling: 4.1,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '32',
    slug: 'fireflies-ai',
    naam: 'Fireflies.ai',
    tagline: 'AI-notulist voor al je meetings',
    beschrijving: 'Fireflies.ai neemt automatisch deel aan je online vergaderingen, transcribeert alles en maakt samenvattingen met actiepunten. Werkt met Zoom, Teams, Google Meet en meer.',
    logo_url: null,
    website_url: 'https://fireflies.ai',
    affiliate_url: null,
    categorie: 'productiviteit',
    prijsmodel: 'freemium',
    plannen: [
      { naam: 'Gratis', prijs_mnd: 0, prijs_jaar: 0, functies: ['800 min opslag', 'AI-samenvattingen', 'Beperkte transcripties'], aanbevolen: false },
      { naam: 'Pro', prijs_mnd: 18, prijs_jaar: 120, functies: ['Onbeperkte transcripties', 'AI-actiepunten', 'CRM-integratie'], aanbevolen: true },
    ],
    beoordeling: 4.3,
    uitgelicht: false,
    badge: 'Tip',
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
  {
    id: '33',
    slug: 'surfer-seo',
    naam: 'Surfer SEO',
    tagline: 'AI-content die rankt op Google',
    beschrijving: 'Surfer SEO analyseert de top-resultaten op Google en genereert content die geoptimaliseerd is om te ranken. Combineert AI-writing met data-gedreven SEO-inzichten. Ideaal voor bloggers en marketeers.',
    logo_url: null,
    website_url: 'https://surferseo.com',
    affiliate_url: null,
    categorie: 'productiviteit',
    prijsmodel: 'betaald',
    plannen: [
      { naam: 'Essential', prijs_mnd: 89, prijs_jaar: 756, functies: ['30 artikelen/mnd', 'Content Editor', 'SERP Analyzer'], aanbevolen: false },
      { naam: 'Scale', prijs_mnd: 129, prijs_jaar: 1104, functies: ['100 artikelen/mnd', 'Auto-interne links', 'Audit tool'], aanbevolen: true },
    ],
    beoordeling: 4.4,
    uitgelicht: false,
    badge: null,
    aangemaakt: '2026-01-01',
    bijgewerkt: '2026-05-01',
  },
]
